import fs from 'node:fs/promises';
import path from 'node:path';
import {createHash} from 'node:crypto';
import {spawn} from 'node:child_process';
import {validateQuartusWorkflow,effectiveQuartusOperationStatus} from './quartus-workflow.mjs';

const hash = text => createHash('sha256').update(text).digest('hex');
// Tcl double-quoted word encoding, independent of model-provided punctuation.
export const quartusTclWord = value => '"'+String(value).replace(/[\\"$\[\]\n\r]/g,c=>({'\\':'\\\\','"':'\\"','$':'\\$','[':'\\[',']':'\\]','\n':'\\n','\r':'\\r'}[c]))+'"';
const q=quartusTclWord;
const SOURCE_ASSIGNMENTS={verilog:'VERILOG_FILE',systemverilog:'SYSTEMVERILOG_FILE',vhdl:'VHDL_FILE'};
export function compileQuartusProject(workflow,{compile=false,target='cli'}={}) {
  if(typeof compile!=='boolean')throw new Error('compile must be boolean');
  if(!['cli','gui'].includes(target))throw new Error('Unsupported Quartus runtime target');
  const w=validateQuartusWorkflow(workflow);
  if(!w.complete)throw new Error('Quartus build blocked: incomplete, unresolved, estimated or missing evidence/source content');
  const applied=new Set(w.operations.filter(o=>effectiveQuartusOperationStatus(o,w)==='applied'&&['create_project','set_project','add_source','set_assignment','set_clock'].includes(o.kind)).flatMap(o=>[...o.sourceEventIds,...w.resolutions.filter(r=>r.operationId===o.id).flatMap(r=>r.sourceEventIds)]));
  if(![w.project,...w.files,...w.assignments,...w.clocks].every(item=>item.evidence.sourceEventIds.some(id=>applied.has(id))))throw new Error('Final state lacks an applied edit operation tied to its evidence');
  const p=w.project;
  const globals=[['FAMILY',p.family],['DEVICE',p.device],['TOP_LEVEL_ENTITY',p.top],['PROJECT_OUTPUT_DIRECTORY','output_files'],...w.assignments.filter(a=>a.target===null).map(a=>[a.name,a.value])];
  const sourceGlobals=w.files.map(f=>[SOURCE_ASSIGNMENTS[f.language],f.path]);
  if(w.clocks.length)sourceGlobals.push(['SDC_FILE','recorded-clocks.sdc']);
  const setGlobals=[...globals,...sourceGlobals].map(([n,v])=>`set_global_assignment -name ${q(n)} ${q(v)}`);
  const setPins=w.assignments.filter(a=>a.target!==null).map(a=>a.name==='LOCATION'?`set_location_assignment ${q(a.value)} -to ${q(a.target)}`:`set_instance_assignment -name ${q(a.name)} ${q(a.value)} -to ${q(a.target)}`);
  const sdcContent='# Periods in nanoseconds; only explicitly recorded primary clocks.\n'+w.clocks.map(c=>`create_clock -name ${q(c.name)} -period ${c.periodNs} [get_ports ${q(c.port)}]`).join('\n')+'\n';
  const contentFiles=w.files.map(f=>({path:f.path,content:f.content}));
  if(w.clocks.length)contentFiles.push({path:'recorded-clocks.sdc',content:sdcContent});
  const checks=[...globals.map(([n,v])=>`assert_equal [get_global_assignment -name ${q(n)}] ${q(v)} ${q(n)}`),
    ...sourceGlobals.map(([n,v])=>`assert_source ${q(n)} ${q(v)}`),
    ...contentFiles.map(f=>`assert_file_content ${q(f.path)} ${q(f.content)}`),
    ...w.assignments.filter(a=>a.target!==null).map(a=>`assert_equal [${a.name==='LOCATION'?`get_location_assignment -to ${q(a.target)}`:`get_instance_assignment -name ${q(a.name)} -to ${q(a.target)}`}] ${q(a.value)} ${q(`${a.name}:${a.target}`)}`)];
  const count=checks.length;
  let script=`# Generated by the local Quartus JSON compiler; never evaluates model Tcl.
package require ::quartus::project
proc assert_equal {actual expected label} {
  if {$actual ne $expected} {error "Readback mismatch: $label"}
}
proc assert_source {assignment expected} {
  set found 0
  foreach_in_collection row [get_all_global_assignments -name $assignment] {
    if {[file normalize [lindex $row 2]] eq [file normalize $expected]} {set found 1}
  }
  if {!$found || ![file isfile $expected]} {error "Missing source assignment: $expected"}
}
proc assert_file_content {name expected} {
  set source [open $name r]
  fconfigure $source -translation lf -encoding utf-8 -eofchar {}
  set actual [read $source]
  close $source
  assert_equal $actual $expected "source content $name"
}
set root [file dirname [file normalize [info script]]]
cd $root
if {[file exists ${q(p.name+'.qpf')}] || [file exists ${q(p.revision+'.qsf')}]} {error "Refusing to overwrite an existing Quartus project"}
set project_opened 0
if {[catch {
  project_new ${q(p.name)} -revision ${q(p.revision)}
  set project_opened 1
${[...setGlobals,...setPins].map(s=>'  '+s).join('\n')}
  export_assignments
  project_close
  set project_opened 0
  project_open ${q(p.name)} -revision ${q(p.revision)}
  set project_opened 1
${checks.map(s=>'  '+s).join('\n')}
${compile?'  package require ::quartus::flow\n  execute_flow -compile\n  if {![file isfile '+q(`output_files/${p.revision}.flow.rpt`)+']} {error "Compile returned without flow report"}':''}
  project_close
  set project_opened 0
  set result [open "quartus-readback.json" {WRONLY CREAT EXCL}]
  puts $result {${JSON.stringify({format:'quartus-readback/1',assignmentChecks:count,assignmentsVerified:true,sourceContentsVerified:true,compileCompleted:compile,logicalEquivalenceVerified:false})}}
  close $result
} failure]} {
  if {$project_opened} {catch {project_close -dont_export_assignments}}
  puts stderr $failure
  exit 1
}
puts "RECORDER_QUARTUS_READBACK_OK"
`;
  if(target==='gui') {
    // Tcl Scripts executes inside the user's app process. Never exit that process,
    // and refuse to touch an already open project. Always restore the app's cwd.
    script=script.replace('  exit 1\n','  error $failure\n');
    script=`# GUI-safe wrapper: only creates a new project when none is open.
package require ::quartus::project
if {[is_project_open]} {error "Recorder build refused: close the current project first"}
set recorder_previous_directory [pwd]
set recorder_build_status [catch {
${script}
} recorder_build_error recorder_build_options]
cd $recorder_previous_directory
if {$recorder_build_status} {return -options $recorder_build_options $recorder_build_error}
`;
  }
  const files=[...contentFiles];
  files.push({path:'build.tcl',content:script});
  return {workflow:w,files,assignmentChecks:count,compileRequested:compile,target};
}
async function noSymlinkParents(target) {
  let current=path.resolve(target);
  while(true) {
    try {const s=await fs.lstat(current);if(s.isSymbolicLink())throw new Error('Output path cannot contain symlinks or junctions');}
    catch(e){if(e.code!=='ENOENT')throw e;}
    const parent=path.dirname(current);if(parent===current)break;current=parent;
  }
}
async function runRuntime(executable,directory,timeoutMs) {
  if(!path.isAbsolute(executable)||!/^quartus_sh(?:\.exe)?$/i.test(path.basename(executable)))throw new Error('Execution requires an explicit absolute quartus_sh executable path');
  const stat=await fs.stat(executable);if(!stat.isFile())throw new Error('Quartus executable is not a file');
  let stdout='',stderr='',timedOut=false;
  const execution=await new Promise(resolve=>{
    const child=spawn(executable,['-t','build.tcl'],{cwd:directory,windowsHide:true,shell:false,stdio:['ignore','pipe','pipe']});
    const timer=setTimeout(()=>{timedOut=true;child.kill();},timeoutMs);
    const cap=(old,chunk)=>(old+chunk.toString('utf8')).slice(-1048576);
    child.stdout.on('data',d=>stdout=cap(stdout,d));child.stderr.on('data',d=>stderr=cap(stderr,d));
    child.once('error',error=>{clearTimeout(timer);resolve({exitCode:null,error:error.message,timedOut});});
    child.once('close',(code,signal)=>{clearTimeout(timer);resolve({exitCode:code,signal,timedOut});});
  });
  await fs.writeFile(path.join(directory,'quartus.stdout.log'),stdout,{flag:'wx'});
  await fs.writeFile(path.join(directory,'quartus.stderr.log'),stderr,{flag:'wx'});
  return {...execution,success:execution.exitCode===0&&!timedOut&&stdout.includes('RECORDER_QUARTUS_READBACK_OK')};
}
export async function writeQuartusProjectArtifacts(output,workflow,options={}) {
  if(typeof output!=='string'||!output.trim())throw new Error('An explicit new output directory is required');
  for(const name of ['compile','execute'])if(options[name]!==undefined&&typeof options[name]!=='boolean')throw new Error(`${name} must be boolean`);
  if(options.compile&&!options.execute)throw new Error('Compilation requires explicit execution');
  if(options.execute&&options.target==='gui')throw new Error('GUI target must be run through Quartus Tcl Scripts, not the CLI execution option');
  if(options.execute&&!options.quartusSh)throw new Error('Execution requires quartusSh');
  const timeout=options.timeoutMs??600000;
  if(!Number.isInteger(timeout)||timeout<1000||timeout>3600000)throw new Error('Runtime timeout must be 1000..3600000 ms');
  const plan=compileQuartusProject(workflow,{compile:options.compile===true,target:options.target??'cli'}),directory=path.resolve(output);
  await noSymlinkParents(directory);
  // Nonrecursive mkdir is the atomic no-overwrite gate; parent must exist.
  await fs.mkdir(directory);
  const artifacts=[];
  const write=async(name,content)=>{await fs.writeFile(path.join(directory,name),content,{flag:'wx'});artifacts.push({path:name,sha256:hash(content),bytes:Buffer.byteLength(content)});};
  for(const f of plan.files)await write(f.path,f.content);
  await write('workflow.json',JSON.stringify(plan.workflow,null,2)+'\n');
  const result={format:'quartus-project-build/1',outputDirectory:directory,generated:true,executed:false,assignmentsVerified:false,sourceContentsVerified:false,compiled:false,logicalEquivalenceVerified:false,
    source:'structured-json',target:plan.target,workflowSha256:hash(JSON.stringify(plan.workflow)),artifacts,
    limitation:'Assignment readback and successful compilation do not prove recording fidelity, timing closure or logical equivalence.',execution:null};
  if(options.execute) {
    result.execution=await runRuntime(options.quartusSh,directory,timeout);result.executed=true;
    if(result.execution.success) {
      try {
        const readback=JSON.parse(await fs.readFile(path.join(directory,'quartus-readback.json'),'utf8'));
        const qpf=await fs.stat(path.join(directory,plan.workflow.project.name+'.qpf'));
        const qsf=await fs.stat(path.join(directory,plan.workflow.project.revision+'.qsf'));
        const contentMatches=(await Promise.all(plan.files.map(async f=>hash(await fs.readFile(path.join(directory,f.path)))===hash(f.content)))).every(Boolean);
        const valid=readback.format==='quartus-readback/1'&&readback.assignmentChecks===plan.assignmentChecks&&readback.assignmentsVerified===true&&readback.sourceContentsVerified===true&&contentMatches&&qpf.isFile()&&qsf.isFile();
        result.assignmentsVerified=valid;
        result.sourceContentsVerified=valid;
        if(options.compile&&valid&&readback.compileCompleted===true){await fs.access(path.join(directory,'output_files',plan.workflow.project.revision+'.flow.rpt'));result.compiled=true;}
        result.readback=readback;
      }catch(error){result.verificationError=error.message;}
    }
  }
  await fs.writeFile(path.join(directory,'build-report.json'),JSON.stringify(result,null,2)+'\n',{flag:'wx'});
  return result;
}
